---
title: "cw4"
author: "Marysia Knapczyk"
format: 
  html:
    self-contained: true
    embed-resources: true
    toc: true
    toc-depth: 4
    toc-location: right
    toc-title: "Spis treści"
    number-sections: true
    number-depth: 4
    code-fold: show
    code-summary: "Show the code"
    code-tools: true
    code-block-bg: true
    code-block-border-left: "black"
    code-line-numbers: false
    code-copy: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    theme:
        light: cosmo
        dark: darkly
    fontsize: 1.0em
    linestretch: 1.5
execute:
  warning: false
  echo: true
  error: false
---

```{r}
library(tidymodels)

# Dodatkowe pakiety
library(rpart.plot)  # wizualizacja drzew decyzyjnych 
library(vip)         # wykres wagi zmiennych
```

### Dane
```{r}
data("cells", package = "modeldata")
cells
```

### Prognoza segmentacji obrazu z optymalizacją hiper-parametrów
```{r}
set.seed(123)
split <- initial_split(data = cells |> select(-case), 
                       prop = 3/4, 
                       strata = class)

train <- training(split)
test <- testing(split)
```

### Optymalizacja
```{r}
tune_spec <- 
  decision_tree(
    cost_complexity = tune(), 
    tree_depth = tune()) |> 
  set_engine("rpart") |> 
  set_mode("classification")

tune_spec
```

```{r}
siatka <- grid_regular(cost_complexity(), 
                       tree_depth(), 
                       levels = 5)
siatka
```

```{r}
# podgląd parametrów 

siatka |> 
  count(tree_depth)
```

```{r}
siatka |> 
  count(cost_complexity)
```

```{r}
set.seed(234)
folds <- vfold_cv(train)
```

```{r}
set.seed(345)

# workflow

work <- 
  workflow() |> 
  add_model(tune_spec) |> 
  add_formula(class ~ .)

# statystyki oceny dokładnosci modelu 

miary_oceny <-
  yardstick::metric_set(# tym parametrem możesz definiować
    accuracy,
    mcc,
    npv,
    roc_auc)

# Optymalizacja 

fit_tree <-
  work |>
  tune_grid(
    resamples = folds,
    grid = siatka,
    metrics = miary_oceny
  )

fit_tree
```

```{r}
fit_tree |> collect_metrics()
```

```{r}
fit_tree %>%
  collect_metrics() %>%
  mutate(tree_depth = factor(tree_depth)) %>%
  ggplot(aes(cost_complexity, mean, color = tree_depth)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) +
  scale_x_log10(labels = scales::label_number()) +
  scale_color_viridis_d(option = "plasma", begin = .9, end = 0)
```

```{r}
fit_tree |> show_best()
```

```{r}
fit_tree |> select_best()
```

### Wybór
```{r}
best_mod <- fit_tree |> select_best()

final_mod <-  
  work |> 
  finalize_workflow(best_mod)
```

```{r}
final_fit <- 
  final_mod |> 
  last_fit(split = split)

final_fit %>%
  collect_metrics()
```

```{r}
final_fit |> 
  collect_predictions() |> 
  roc_curve(truth = class, .pred_PS) |> 
  autoplot()
```

```{r}
final_fit |> extract_workflow()
```

```{r}
final_fit |> 
  extract_workflow() |> 
  extract_fit_engine() |> 
  rpart.plot(roundint = F)
```

```{r}
# wykres 

final_fit |> 
  extract_workflow() |> 
  extract_fit_parsnip() |>
  vip() 
```

```{r}
# eksport danych do tabeli

final_fit |>
  extract_workflow() |>
  extract_fit_parsnip() |>
  vip() |> 
  _$data |> 
  knitr::kable(digits = 1)
```

```{r}
args(decision_tree)

```
Mozna dostrajac: cost_complexity, tree_depth oraz min_n. Mozna tez zmienic engine. 
