---
title: "prognoza"
author: "Marysia"
format: 
  html:
    self-contained: true
    embed-resources: true
    toc: true
    toc-depth: 4
    toc-location: right
    toc-title: "Spis treści"
    number-sections: true
    number-depth: 4
    code-fold: show
    code-summary: "Show the code"
    code-tools: true
    code-block-bg: true
    code-block-border-left: "black"
    code-line-numbers: false
    code-copy: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    theme:
        light: cosmo
        dark: darkly
    fontsize: 1.0em
    linestretch: 1.5
execute:
  warning: false
  echo: true
  error: false
---
```{r}
library(GGally)
library(tidymodels)
library(parsnip)
```


```{r}
colnames(airquality) <- tolower(colnames(airquality))

air <-
  airquality |>
  as_tibble() |>
  na.omit() |> 
  select(-day) |> 
  mutate(month = factor(month)) 
```

```{r}
ggpairs(airquality[, c("ozone", "solar.r", "wind", "temp", "month")])
```
```{r}
air
```

```{r}
set.seed(111)
split <- initial_split(air, prop = 3/4)
train_data <- training(split)
test_data  <- testing(split)
```

```{r}
lm_mod <- 
  linear_reg() |> 
  set_engine("lm")
```

```{r}
lm_fit <-  
  lm_mod |>
  fit(ozone ~ solar.r + wind + temp + month, data = train_data)
lm_fit  
```

```{r}
lm_fit$fit  |> summary()
```
Temperatura - pozytywny i statystycznie istotny wpływ na poziom ozonu.
Wiatr - negatywny i statystycznie istostny wpływa na poziom ozonu.
Solar.r - umiarkowane działanie i wpływ 
```{r}
mean_pred <- predict(object = lm_fit, new_data = test_data)
```

```{r}
conf_pred <- predict(lm_fit, new_data = test_data, type = "conf_int")
```

```{r}
results <- bind_cols(test_data, mean_pred, conf_pred) |> 
  rename(predicted_ozone = .pred)

results
```

```{r}
ggplot(results, aes(x = ozone, y = predicted_ozone)) +
  geom_point(color = "pink") +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "purple") +
  labs(title = "Predykcja wartości ozonu z linią perfekcyjnego przewidywania", x = "Rzeczywista wartość", y = "Przewidywana wartość") +
  theme_minimal()
```
Model ma problem szczególnie z przewidywaniem wyższych wartości. 
```{r}
ggplot(results, aes(x = ozone, y = predicted_ozone)) +
  geom_point(color = "pink") +
  geom_errorbar(aes(ymin = .pred_lower, ymax = .pred_upper), 
                width = 0.1, color = "gray") +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "purple") +
  labs(title = "Predykcja wartości ozonu z przedziałami ufności",
       x = "Rzeczywista wartość", y = "Przewidywana wartość") +
  theme_minimal()

```
Przedziały ufności są bardzo szerokie, jest spory poziom niepewności i błędu.
